apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 3  # Adjust based on your scaling requirements
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: your-docker-username/wordpress:latest  # Adjust based on your Docker image
        ports:
        - containerPort: 80
